name: Update Meson Build

on:
  push:
    paths:
      - '**/*'

jobs:
  update_meson_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Python Script
      run: |
        python3 update.py
      working-directory: ${{ github.workspace }}

    - name: Commit Changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add meson.build
        git commit -m "Update Meson build script [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
