name: CI Process

on:
  push:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.c"
      - "**.h"
      - "**.py"
      - "**.build"

permissions:
  contents: read

jobs:
  host_macosx:
    strategy:
      matrix:
        os: [10.15, 11, 12, 13]  # macOS versions
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Required Tools
      run: |
          pip install -r .github/requirements.txt
          python .github/dependencies.py
    - name: Setup Build Directory
      run: |
            python .github/fossil-tool.py setup
    - name: Compile Source Code
      run: |
            python .github/fossil-tool.py compile

  host_windows:
    strategy:
      matrix:
        os: ['windows-latest', 'windows-2022']
        mingw: [false, 'mingw32', 'mingw64', 'MSYS']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: x64
    - name: Setup MinGW/MSYS
      if: matrix.mingw != false
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.mingw }}
        update: true
    - name: Install Required Tools
      run: |
          pip install -r .github/requirements.txt
          python .github/dependencies.py
    - name: Setup Build Directory
      run: |
            python .github/fossil-tool.py setup
    - name: Compile Source Code
      run: |
            python .github/fossil-tool.py compile

  host_ubuntu:
    strategy:
      matrix:
        ubuntu_version: ['latest', '22.04']
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Required Tools
      run: |
          pip install -r .github/requirements.txt
          python .github/dependencies.py
    - name: Setup Build Directory
      run: |
            python .github/fossil-tool.py setup
    - name: Compile Source Code
      run: |
            python .github/fossil-tool.py compile
