name: CI Process

on:
  push:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.c"
      - "**.h"
      - "**.py"
      - "**.pyx"
      - "**.rs"
      - "**.build"

permissions:
  contents: read

jobs:
  common_steps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: x64
    - name: Install Required Tools
      run: |
        python -m pip install -r .github/requirements.txt
        python .github/dependencies.py

  host_macosx:
    needs: common_steps
    strategy:
      matrix:
        os: [10.15, 11, 12, 13]
    runs-on: macos-latest
    steps:
    - name: Setup Project Code
      run: meson setup builddir
    - name: Setup Project Code
      run: meson compile -C builddir -v

  host_windows:
    needs: common_steps
    strategy:
      matrix:
        os: ['windows-latest', 'windows-2022']
        mingw: [false, 'mingw32', 'mingw64', 'MSYS']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup MinGW/MSYS
      if: matrix.mingw != false
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.mingw }}
        update: true
    - name: Setup Project Code
      run: meson setup builddir
    - name: Setup Project Code
      run: meson compile -C builddir -v

  host_ubuntu:
    needs: common_steps
    strategy:
      matrix:
        ubuntu_version: ['latest', '22.04']
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    steps:
    - name: Setup Project Code
      run: meson setup builddir
    - name: Setup Project Code
      run: meson compile -C builddir -v
